"use client";

import { useEffect, useState } from "react";
import { supabase, Generation } from "@/lib/supabase";
import { useRouter } from "next/navigation";
import Image from "next/image";
import Link from "next/link";

export default function GalleryPage() {
  const [generations, setGenerations] = useState<Generation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<"all" | "image" | "video">("all");
  const [selectedModel, setSelectedModel] = useState<string>("all");
  const router = useRouter();

  useEffect(() => {
    loadGallery();
  }, [filter, selectedModel]);

  async function loadGallery() {
    try {
      setLoading(true);
      setError(null);
      
      // Check if Supabase is properly configured
      const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
      if (!supabaseUrl || supabaseUrl.includes('example') || supabaseUrl.includes('placeholder')) {
        setError("Gallery database not configured. Set up Supabase to enable the community gallery.");
        setLoading(false);
        return;
      }

      let query = supabase
        .from("generations")
        .select("*")
        .eq("is_public", true)
        .order("created_at", { ascending: false })
        .limit(50);

      if (filter !== "all") {
        query = query.eq("generation_type", filter);
      }

      if (selectedModel !== "all") {
        query = query.eq("model_id", selectedModel);
      }

      const { data, error: queryError } = await query;

      if (queryError) {
        // Check if it's a connection error
        if (queryError.message?.includes('fetch') || queryError.code === '') {
          setError("Unable to connect to the gallery database. Please check your Supabase configuration.");
        } else {
          setError(queryError.message || "Failed to load gallery");
        }
        return;
      }
      
      setGenerations(data || []);
    } catch (err: any) {
      console.error("Error loading gallery:", err);
      setError("Unable to load gallery. The database may not be configured.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="flex-1 w-full px-4 md:px-10 py-8 space-y-8">
      <header className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <h1 className="text-3xl md:text-5xl font-semibold text-gradient">
            Public Gallery
          </h1>
          <p className="text-white/70 mt-2">
            Browse images and videos generated by the community
          </p>
        </div>
        <div className="flex gap-4">
          <Link
            href="/create"
            className="px-6 py-2 rounded-full bg-gradient-to-r from-orange-500 to-yellow-400 text-black font-semibold hover:opacity-90 transition"
          >
            Create
          </Link>
          <Link
            href="/profile"
            className="px-6 py-2 rounded-full border border-white/20 text-white/70 hover:text-white hover:border-white/40 transition"
          >
            My Creations
          </Link>
        </div>
      </header>

      <div className="flex flex-wrap gap-4 items-center">
        <div className="flex gap-2">
          <button
            onClick={() => setFilter("all")}
            className={`px-4 py-2 rounded-full border transition ${
              filter === "all"
                ? "border-white text-white bg-white/10"
                : "border-white/20 text-white/70 hover:text-white"
            }`}
          >
            All
          </button>
          <button
            onClick={() => setFilter("image")}
            className={`px-4 py-2 rounded-full border transition ${
              filter === "image"
                ? "border-white text-white bg-white/10"
                : "border-white/20 text-white/70 hover:text-white"
            }`}
          >
            Images
          </button>
          <button
            onClick={() => setFilter("video")}
            className={`px-4 py-2 rounded-full border transition ${
              filter === "video"
                ? "border-white text-white bg-white/10"
                : "border-white/20 text-white/70 hover:text-white"
            }`}
          >
            Videos
          </button>
        </div>
      </div>

      {loading ? (
        <div className="text-center text-white/50 py-20">
          Loading gallery...
        </div>
      ) : error ? (
        <div className="text-center py-20">
          <div className="panel max-w-md mx-auto space-y-4">
            <div className="text-4xl">🖼️</div>
            <h2 className="text-xl font-semibold text-white">Gallery Unavailable</h2>
            <p className="text-white/70">{error}</p>
            <p className="text-white/50 text-sm">
              Generated images and videos will appear here once the database is configured.
            </p>
            <Link 
              href="/create"
              className="inline-block px-6 py-2 rounded-full bg-gradient-to-r from-orange-500 to-yellow-400 text-black font-semibold hover:opacity-90 transition"
            >
              Start Creating
            </Link>
          </div>
        </div>
      ) : generations.length === 0 ? (
        <div className="text-center text-white/50 py-20">
          No generations found. Be the first to create something!
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          {generations.map((gen) => (
            <GalleryItem key={gen.id} generation={gen} />
          ))}
        </div>
      )}
    </main>
  );
}

function GalleryItem({ generation }: { generation: Generation }) {
  const [imageError, setImageError] = useState(false);

  return (
    <div className="panel group cursor-pointer hover:scale-105 transition-transform">
      <div className="relative aspect-square rounded-xl overflow-hidden bg-black/40">
        {generation.generation_type === "video" ? (
          <video
            src={generation.media_url || undefined}
            className="w-full h-full object-cover"
            controls
            muted
            onError={() => setImageError(true)}
          />
        ) : generation.media_base64 ? (
          <img
            src={generation.media_base64}
            alt={generation.prompt}
            className="w-full h-full object-cover"
            onError={() => setImageError(true)}
          />
        ) : generation.media_url ? (
          <img
            src={generation.media_url}
            alt={generation.prompt}
            className="w-full h-full object-cover"
            onError={() => setImageError(true)}
          />
        ) : (
          <div className="w-full h-full flex items-center justify-center text-white/30">
            No preview
          </div>
        )}
        {generation.is_nsfw && (
          <div className="absolute top-2 right-2 px-2 py-1 bg-red-500/80 text-white text-xs rounded">
            NSFW
          </div>
        )}
      </div>
      <div className="p-4 space-y-2">
        <p className="text-sm text-white/90 line-clamp-2">{generation.prompt}</p>
        <div className="flex items-center justify-between text-xs text-white/50">
          <span>{generation.model_id}</span>
          <span>{new Date(generation.created_at).toLocaleDateString()}</span>
        </div>
      </div>
    </div>
  );
}

